version: "3.7"

services:
    redis:
        image: redis:6
        volumes:
            - redis-data:/data
        command: redis-server --requirepass ${redis_pass}
    sql:
        image: postgres:13-alpine
        env_file:
            - .env
        volumes:
            - pg-data:/var/lib/postgresql/data
    web:
        build: .
        image: pharmacy
        env_file:
            - .env
        ports:
            - "9560:9560"
        depends_on:
            - sql
            - redis

volumes:
    pg-data:
    redis-data:
